project_id: '1'
base_url: 'https://bluesky.api.crowdin.com'
base_path: .
preserve_hierarchy: 1
files:
  - source: /src/locale/locales/ms-MY/messages.po
    translation: /src/locale/locales/%two_letters_code%/messages.po
